In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
%pip install -q decorator==5.0.9
!pip install -q ipywidgets

import re
import imp
import json
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import networkx as nx
import seaborn as sns
from collections import Counter

import ipywidgets as widgets
from ipywidgets import interact, interact_manual

Note: you may need to restart the kernel to use updated packages.


In [3]:
%pip install -q cltk==1.0.22
%pip install -q strsim
%pip install -q leven

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [4]:
# importing local modules

import sys
sys.path.append('../src/')

import text_cleanup.text_cleanup as thesisCleanUp
import preprocessing.text_preprocessing as thesisTextPreprocessing
import data.reader as thesisDataReader
import utils.utils as thesisUtils
import features.tf_idf.n_gram as thesisTfIdfNgramFeatures
import features.count_vectorizer.n_gram as thesisCountVectorizerNgramFeatures
import similarities.cosine as thesisCosineSimilarities
import similarities.levenshtein as thesisLevenshteinSimilarities
import vocabulary.vocabulary as thesisVocabulary
import features.lexical as thesisLexicalFeatures
import similarities.cosine as thesisCosineSimilarity
import text_cleanup.text_cleanup as thesisTextCleanUp
import p_aligment.p_aligment as thesisPAligment
import features.model_features as thesisModelFeatures

imp.reload(thesisTfIdfNgramFeatures)
imp.reload(thesisLexicalFeatures)
imp.reload(thesisCosineSimilarity)
imp.reload(thesisCleanUp)
imp.reload(thesisTextPreprocessing)
imp.reload(thesisDataReader)
imp.reload(thesisUtils)

imp.reload(thesisVocabulary)
imp.reload(thesisCosineSimilarities)
imp.reload(thesisTextCleanUp)
imp.reload(thesisCountVectorizerNgramFeatures)
imp.reload(thesisPAligment)
imp.reload(thesisLevenshteinSimilarities)
imp.reload(thesisModelFeatures)

<module 'features.model_features' from '../src/features/model_features.py'>

In [5]:
breslau_corpus = thesisDataReader.CorpusByNewLine.breslau()

In [25]:
london_vs_burchard_best_model = thesisModelFeatures.get_london_vs_burchard_best_model()
zwickau_vs_burchard_best_model = thesisModelFeatures.get_zwickau_vs_burchard_best_model()
london_vs_zwickau_best_model = thesisModelFeatures.get_london_vs_zwickau_best_model()

In [9]:
breslau_features_by_london_vectorizer = thesisModelFeatures.create_features_df(
    breslau_corpus.corpus,
    None,
    None,
    n_gram = (2,5),
    features = { 'tfidf', 'inner_mean_cosine_similarity_score' },
    vectorizer = thesisModelFeatures.load_london_burchard_vectorizer('features_tfidf_2_5_gram_cosine_similarity_long_p')
)

n_gram_feature_name: 2_5_gram


In [11]:
X_breslau, y_breslau = thesisModelFeatures.create_X_y(breslau_features_by_london_vectorizer)

In [12]:
london_vs_burchard_classifier_on_breslau_resuts = london_vs_burchard_best_model.predict(X_breslau)

In [13]:
london_vs_burchard_classifier_on_breslau_resuts

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 0., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 0., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2.])

In [14]:
breslau_features_by_zwickau_vectorizer = thesisModelFeatures.create_features_df(
    breslau_corpus.corpus,
    None,
    None,
    n_gram = (2,5),
    features = { 'tfidf', 'inner_mean_cosine_similarity_score' },
    vectorizer = thesisModelFeatures.load_zwickau_burchard_vectorizer('features_tfidf_2_5_gram_cosine_similarity_long_p')
)

n_gram_feature_name: 2_5_gram


In [15]:
X_breslau, y_breslau = thesisModelFeatures.create_X_y(breslau_features_by_zwickau_vectorizer)

In [16]:
zwickau_vs_burchard_classifier_on_breslau_resuts = zwickau_vs_burchard_best_model.predict(X_breslau)

In [17]:
zwickau_vs_burchard_classifier_on_breslau_resuts

array([2., 2., 2., 2., 2., 1., 1., 1., 2., 2., 2., 2., 1., 2., 2., 2., 1.,
       1., 2., 1., 2., 2., 1., 1., 2., 2., 1., 1., 2., 1., 2., 2., 2., 1.,
       2., 2., 1., 2., 2., 1., 2., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2.,
       2., 1., 2., 2., 2., 2., 2., 2., 1., 2., 1., 2., 1., 1., 2., 2., 2.,
       2., 2., 1.])

In [26]:
breslau_features_by_london_zwickau_vectorizer = thesisModelFeatures.create_features_df(
    breslau_corpus.corpus,
    None,
    None,
    n_gram = (2,5),
    features = { 'tfidf', 'inner_mean_cosine_similarity_score' },
    vectorizer = thesisModelFeatures.load_london_zwickau_vectorizer('features_tfidf_2_5_gram_cosine_similarity_long_p')
)

n_gram_feature_name: 2_5_gram


In [27]:
X_breslau, y_breslau = thesisModelFeatures.create_X_y(breslau_features_by_london_zwickau_vectorizer)

In [28]:
london_vs_zwickau_classifier_on_breslau_resuts = london_vs_zwickau_best_model.predict(X_breslau)

In [29]:
london_vs_zwickau_classifier_on_breslau_resuts

array([0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1.,
       1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1.,
       0., 1., 0.])

In [30]:
data = [
    [
        p, 
        thesisModelFeatures.version_label_to_human_readable(london_vs_burchard_classifier_on_breslau_resuts[i]),
        thesisModelFeatures.version_label_to_human_readable(zwickau_vs_burchard_classifier_on_breslau_resuts[i]),
        thesisModelFeatures.version_label_to_human_readable(london_vs_zwickau_classifier_on_breslau_resuts[i]),
    ]
    for i, p in enumerate(breslau_corpus.corpus)
]

In [34]:
pd.DataFrame(
    data, 
    columns = ['breslau text', 'london VS burchard classifier', 'zwickau VS burchard classifier', 'london VS zwickau classifier']
).to_csv('../computed_data/models/breslau/breslau_predictions.csv')